### ISSUE TITLE
Support Administrate 0.18

### ISSUE THREAD

**Issue by tancrede** [fishpercolator/administrate-field-lat_lng#12]
Dear maintainer,

I've been running a fork of your excellent gem on my app with administrate 0.18 and all seems good.

Bumping the gemspec might be safe

Thanks

**Comment by tancrede** [comment]
#13

**Comment by pedantic-git** [comment]
Hi @tancrede - thanks so much! It still passes tests with 0.18 so I've merged your PR and released a new version of the gem as v1.17.0.
