### ISSUE TITLE
Possible to support Administrate 0.7.0?

### ISSUE THREAD

**Issue by lucaskuan** [fishpercolator/administrate-field-lat_lng#7]
I'm using Administrate v0.7.0 and super happy to see this gem and would like it works on v0.7.0.
Base on the [Release note](https://github.com/thoughtbot/administrate/releases). Looks like no changes would impact this gem. I also fork this repo and try, no critical error so far.
Please check if it is possible and update the gemspec 👍

**Comment by pedantic-git** [comment]
Thanks for using my gem! I've made this change now and released it as 1.6.0. Please reopen and let me know if you have any issues!
